### PR TITLE
Add Tests, CI and Licence

### PR DESCRIPTION
**Pull request by fkanout**
Hi,

I'm using this module in my project, and I wanted to increase its quality by covering it with tests and CI integration.  

Heads-up:
The CI is linked to my account, so feel free to re-link it to yours.

Do not hesitate to ping me if you have any questions
 
Faisal

### CODE REVIEW

**Comment by gluxon** [comment]
@fkanout This looks awesome. Thanks for taking the time to make this. A few notes:

1. Since I've made the project, I've actually discovered that the `koa-csrf` does in fact check for CSRF tokens in the header. It's just not documented: https://github.com/koajs/csrf/blob/master/src/index.js#L57

2. There was no way for you to know this since I hadn't documented it, but could you make sure your changes pass the `npx standard` command? I'd be happy to accept your pull request once that change is made.

**Comment by fkanout** [comment]
@gluxon, thanks for letting me know that `koa-csrf` has this feature. !
and the `standard` linting is applied

**Comment by fkanout** [comment]
otherwise, after the merge, it's gonna be deployed to `npm` automatically ?

**Comment by fkanout** [comment]
I've just checked the codebase of `koa-csrf`, that's correct it supports CSRF headers, but still can't use cookies.
Plus, it's great to have the control to change header field name and how to get and set the token

**Comment by gluxon** [comment]
> otherwise, after the merge, it's gonna be deployed to npm automatically ?

Nothing automatic is set up. I don't see any changes to `index.js`, do you think a deploy to npm is necessary?

> The CI is linked to my account, so feel free to re-link it to yours.

I'm okay leaving it linked to your CI if you are.

**Pull request merged**
